version: '2'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: room_status
            MYSQL_USER: docker
            MYSQL_PASSWORD: qwer1234
            TZ: 'Asia/Tokyo'
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    phpmyadmin:
        depends_on:
            - mysql
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOSTS: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8080:80

    web:
        depends_on:
            - mysql
        container_name: web
        build:
            context: ./docker/api
            dockerfile: Dockerfile
        ports:
            - 80:80
